import { ExternalTask } from '../types';

export const initialTasks: ExternalTask[] = [
  {
    id: 'clickup:101',
    externalId: '101',
    provider: 'clickup',
    title: 'Implementar autenticação e armazenamento seguro',
    description: 'Integrar Keychain no macOS para armazenar o token da API sem expor em texto plano no banco local.',
    status: {
      id: 'in_progress',
      name: 'IN PROGRESS',
      color: '#3b82f6',
      isDone: false,
    },
    availableStatuses: [
      { id: 'to_do', name: 'TO DO', color: '#87909e' },
      { id: 'in_progress', name: 'IN PROGRESS', color: '#3b82f6' },
      { id: 'review', name: 'REVIEW', color: '#a855f7' },
      { id: 'done', name: 'DONE', color: '#10b981', isDone: true },
    ],
    sourceId: 'list_1',
    sourceName: 'Sprint 14',
    dueDate: 'Hoje, 18:00',
    url: 'https://app.clickup.com/t/101',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'clickup:102',
    externalId: '102',
    provider: 'clickup',
    title: 'Corrigir formulário de criação rápida de tarefas',
    description: 'Adicionar validação de campos obrigatórios e feedback de sucesso imediato com animação.',
    status: {
      id: 'to_do',
      name: 'TO DO',
      color: '#87909e',
      isDone: false,
    },
    availableStatuses: [
      { id: 'to_do', name: 'TO DO', color: '#87909e' },
      { id: 'in_progress', name: 'IN PROGRESS', color: '#3b82f6' },
      { id: 'done', name: 'DONE', color: '#10b981', isDone: true },
    ],
    sourceId: 'list_1',
    sourceName: 'Sprint 14',
    dueDate: 'Amanhã',
    url: 'https://app.clickup.com/t/102',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'clickup:103',
    externalId: '103',
    provider: 'clickup',
    title: 'Revisar Pull Request da abstração TaskProvider',
    description: 'Garantir que regras de negócio do ClickUp estão 100% isoladas na camada de provedores.',
    status: {
      id: 'in_progress',
      name: 'IN PROGRESS',
      color: '#3b82f6',
      isDone: false,
    },
    availableStatuses: [
      { id: 'to_do', name: 'TO DO', color: '#87909e' },
      { id: 'in_progress', name: 'IN PROGRESS', color: '#3b82f6' },
      { id: 'done', name: 'DONE', color: '#10b981', isDone: true },
    ],
    sourceId: 'list_1',
    sourceName: 'Sprint 14',
    dueDate: 'Hoje',
    url: 'https://app.clickup.com/t/103',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'clickup:104',
    externalId: '104',
    provider: 'clickup',
    title: 'Atualizar documentação de arquitetura no context.md',
    description: 'Refletir a decisão da aba lateral retrátil e fluxo offline-first.',
    status: {
      id: 'done',
      name: 'DONE',
      color: '#10b981',
      isDone: true,
    },
    availableStatuses: [
      { id: 'to_do', name: 'TO DO', color: '#87909e' },
      { id: 'done', name: 'DONE', color: '#10b981', isDone: true },
    ],
    sourceId: 'list_2',
    sourceName: 'Backlog Produto',
    dueDate: null,
    url: 'https://app.clickup.com/t/104',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'clickup:105',
    externalId: '105',
    provider: 'clickup',
    title: 'Testar animação da aba lateral no macOS',
    description: 'Verificar a suavidade do recolhimento e expansão do drawer lateral.',
    status: {
      id: 'to_do',
      name: 'TO DO',
      color: '#87909e',
      isDone: false,
    },
    availableStatuses: [
      { id: 'to_do', name: 'TO DO', color: '#87909e' },
      { id: 'in_progress', name: 'IN PROGRESS', color: '#3b82f6' },
      { id: 'done', name: 'DONE', color: '#10b981', isDone: true },
    ],
    sourceId: 'list_2',
    sourceName: 'Backlog Produto',
    dueDate: '10 de Set',
    url: 'https://app.clickup.com/t/105',
    updatedAt: new Date().toISOString(),
  },
];
